"""Food shelf-life knowledge base.

Shelf lives are conservative "use by" estimates in days, assuming normal
storage (refrigerated where appropriate). Sources: USDA FoodKeeper data,
rounded down to be safe.
"""

from __future__ import annotations

from lettuceremind.models import FoodInfo

# Default shelf life (days) per category, used when an item has no override.
CATEGORY_SHELF_LIFE: dict[str, int] = {
    "leafy greens": 5,
    "fresh fruit": 7,
    "fresh vegetables": 10,
    "fresh herbs": 7,
    "milk & cream": 7,
    "cheese": 21,
    "yogurt & cultured": 14,
    "butter & spreads": 60,
    "eggs": 35,
    "fresh meat": 3,
    "fresh poultry": 2,
    "deli meat": 5,
    "seafood": 2,
    "bakery": 5,
    "frozen": 180,
    "pantry staples": 365,
    "canned goods": 730,
    "beverages": 180,
    "snacks": 90,
    "condiments & sauces": 180,
    "baby & health": 365,
    "household": 3650,
    "other": 7,
}

DEFAULT_CATEGORY = "other"
DEFAULT_SHELF_LIFE_DAYS = CATEGORY_SHELF_LIFE[DEFAULT_CATEGORY]


def _f(name: str, category: str, *aliases: str, days: int | None = None) -> FoodInfo:
    return FoodInfo(name=name, category=category, aliases=tuple(aliases), shelf_life_days=days)


FOOD_DB: tuple[FoodInfo, ...] = (
    # ---- Leafy greens ----
    _f("lettuce", "leafy greens", "iceberg lettuce", "head lettuce"),
    _f("romaine lettuce", "leafy greens", "romaine", "romaine hearts"),
    _f("spinach", "leafy greens", "baby spinach"),
    _f("kale", "leafy greens", "baby kale"),
    _f("arugula", "leafy greens"),
    _f("spring mix", "leafy greens", "salad mix", "mixed greens", "salad blend"),
    _f("cabbage", "leafy greens", "green cabbage", "red cabbage", days=30),
    _f("swiss chard", "leafy greens", "chard"),
    _f("bok choy", "leafy greens"),
    _f("collard greens", "leafy greens", "collards"),
    # ---- Fresh fruit ----
    _f("bananas", "fresh fruit", "banana"),
    _f("apples", "fresh fruit", "apple", "gala apples", "fuji apples", "honeycrisp apples", days=21),
    _f("oranges", "fresh fruit", "orange", "navel oranges", days=14),
    _f("mandarins", "fresh fruit", "mandarin", "clementines", "clementine", days=14),
    _f("grapes", "fresh fruit", "red grapes", "green grapes", "seedless grapes"),
    _f("strawberries", "fresh fruit", "strawberry", days=5),
    _f("blueberries", "fresh fruit", "blueberry", days=10),
    _f("raspberries", "fresh fruit", "raspberry", days=3),
    _f("blackberries", "fresh fruit", "blackberry", days=5),
    _f("watermelon", "fresh fruit", days=14),
    _f("cantaloupe", "fresh fruit", "melon", days=10),
    _f("pineapple", "fresh fruit", days=5),
    _f("mango", "fresh fruit", "mangoes", days=6),
    _f("peaches", "fresh fruit", "peach", days=4),
    _f("nectarines", "fresh fruit", "nectarine", days=4),
    _f("plums", "fresh fruit", "plum", days=5),
    _f("pears", "fresh fruit", "pear", "bartlett pears", days=7),
    _f("cherries", "fresh fruit", "cherry", days=6),
    _f("kiwi", "fresh fruit", "kiwifruit", days=7),
    _f("lemons", "fresh fruit", "lemon", days=21),
    _f("limes", "fresh fruit", "lime", days=21),
    _f("grapefruit", "fresh fruit", days=14),
    _f("avocado", "fresh fruit", "avocados", "hass avocado", days=4),
    _f("pomegranate", "fresh fruit", days=14),
    # ---- Fresh vegetables ----
    _f("tomatoes", "fresh vegetables", "tomato", "roma tomatoes", "cherry tomatoes",
       "grape tomatoes", "tomatoes on the vine", days=6),
    _f("potatoes", "fresh vegetables", "potato", "russet potatoes", "red potatoes",
       "gold potatoes", "yukon gold potatoes", days=30),
    _f("sweet potatoes", "fresh vegetables", "sweet potato", "yams", days=21),
    _f("onions", "fresh vegetables", "onion", "yellow onions", "red onions",
       "white onions", "sweet onions", days=30),
    _f("green onions", "fresh vegetables", "scallions", "green onion", days=7),
    _f("garlic", "fresh vegetables", days=90),
    _f("carrots", "fresh vegetables", "carrot", "baby carrots", days=21),
    _f("celery", "fresh vegetables", days=14),
    _f("broccoli", "fresh vegetables", "broccoli crowns", days=7),
    _f("cauliflower", "fresh vegetables", days=7),
    _f("bell peppers", "fresh vegetables", "bell pepper", "green peppers",
       "red peppers", "yellow peppers", "peppers", days=10),
    _f("jalapenos", "fresh vegetables", "jalapeno", "jalapeno peppers", days=10),
    _f("cucumbers", "fresh vegetables", "cucumber", "english cucumber", days=7),
    _f("zucchini", "fresh vegetables", "squash", "yellow squash", days=5),
    _f("mushrooms", "fresh vegetables", "mushroom", "white mushrooms",
       "baby bella mushrooms", "portabella mushrooms", days=7),
    _f("asparagus", "fresh vegetables", days=4),
    _f("green beans", "fresh vegetables", "string beans", days=7),
    _f("corn", "fresh vegetables", "sweet corn", "corn on the cob", days=3),
    _f("brussels sprouts", "fresh vegetables", "brussel sprouts", days=10),
    _f("eggplant", "fresh vegetables", days=7),
    _f("radishes", "fresh vegetables", "radish", days=14),
    _f("beets", "fresh vegetables", "beet", days=14),
    _f("ginger", "fresh vegetables", "ginger root", days=30),
    _f("butternut squash", "fresh vegetables", days=30),
    # ---- Fresh herbs ----
    _f("cilantro", "fresh herbs"),
    _f("parsley", "fresh herbs"),
    _f("basil", "fresh herbs", days=5),
    _f("mint", "fresh herbs"),
    _f("rosemary", "fresh herbs", days=14),
    _f("thyme", "fresh herbs", days=14),
    _f("dill", "fresh herbs"),
    # ---- Milk & cream ----
    _f("milk", "milk & cream", "whole milk", "2% milk", "1% milk", "skim milk",
       "vitamin d milk", "reduced fat milk", "fat free milk"),
    _f("almond milk", "milk & cream", "almondmilk", days=10),
    _f("oat milk", "milk & cream", "oatmilk", days=10),
    _f("soy milk", "milk & cream", "soymilk", days=10),
    _f("half and half", "milk & cream", days=10),
    _f("heavy cream", "milk & cream", "heavy whipping cream", "whipping cream", days=14),
    _f("coffee creamer", "milk & cream", "creamer", days=14),
    _f("buttermilk", "milk & cream", days=14),
    _f("eggnog", "milk & cream", days=7),
    # ---- Cheese ----
    _f("cheddar cheese", "cheese", "cheddar", "sharp cheddar", "mild cheddar"),
    _f("mozzarella cheese", "cheese", "mozzarella", "fresh mozzarella"),
    _f("parmesan cheese", "cheese", "parmesan", "grated parmesan", days=60),
    _f("swiss cheese", "cheese"),
    _f("provolone cheese", "cheese", "provolone"),
    _f("american cheese", "cheese", "american singles", "cheese singles"),
    _f("shredded cheese", "cheese", "shredded cheddar", "shredded mozzarella",
       "mexican blend cheese", "colby jack"),
    _f("cream cheese", "cheese", days=30),
    _f("cottage cheese", "cheese", days=10),
    _f("feta cheese", "cheese", "feta", days=30),
    _f("goat cheese", "cheese", days=14),
    _f("string cheese", "cheese", "cheese sticks", days=30),
    _f("ricotta cheese", "cheese", "ricotta", days=10),
    _f("brie", "cheese", "brie cheese", days=14),
    # ---- Yogurt & cultured ----
    _f("yogurt", "yogurt & cultured", "greek yogurt", "vanilla yogurt", "strawberry yogurt"),
    _f("sour cream", "yogurt & cultured", days=21),
    _f("kefir", "yogurt & cultured"),
    # ---- Butter & spreads ----
    _f("butter", "butter & spreads", "salted butter", "unsalted butter"),
    _f("margarine", "butter & spreads"),
    _f("hummus", "butter & spreads", days=7),
    _f("guacamole", "butter & spreads", days=3),
    # ---- Eggs ----
    _f("eggs", "eggs", "large eggs", "dozen eggs", "grade a eggs", "egg"),
    _f("egg whites", "eggs", "liquid egg whites", days=7),
    # ---- Fresh meat ----
    _f("ground beef", "fresh meat", "ground chuck", "lean ground beef", "hamburger meat", days=2),
    _f("beef steak", "fresh meat", "ribeye steak", "sirloin steak", "ny strip steak",
       "t-bone steak", "steak", "filet mignon"),
    _f("beef roast", "fresh meat", "chuck roast", "pot roast", "rump roast"),
    _f("stew meat", "fresh meat", "beef stew meat", days=2),
    _f("pork chops", "fresh meat", "pork chop", "pork loin chops"),
    _f("pork loin", "fresh meat", "pork tenderloin", "pork roast"),
    _f("ground pork", "fresh meat", days=2),
    _f("bacon", "fresh meat", days=7),
    _f("sausage", "fresh meat", "breakfast sausage", "italian sausage", "pork sausage", days=2),
    _f("ground lamb", "fresh meat", "lamb", days=2),
    _f("ribs", "fresh meat", "pork ribs", "baby back ribs", "spare ribs"),
    # ---- Fresh poultry ----
    _f("chicken breast", "fresh poultry", "chicken breasts", "boneless chicken breast",
       "boneless skinless chicken breast", "chicken breast fillets"),
    _f("chicken thighs", "fresh poultry", "chicken thigh", "boneless chicken thighs"),
    _f("chicken wings", "fresh poultry", "chicken wing", "party wings"),
    _f("chicken drumsticks", "fresh poultry", "drumsticks", "chicken legs"),
    _f("whole chicken", "fresh poultry", "roasting chicken"),
    _f("rotisserie chicken", "fresh poultry", days=4),
    _f("ground chicken", "fresh poultry"),
    _f("ground turkey", "fresh poultry", "lean ground turkey"),
    _f("turkey breast", "fresh poultry"),
    # ---- Deli meat ----
    _f("deli ham", "deli meat", "sliced ham", "honey ham", "black forest ham", "ham"),
    _f("deli turkey", "deli meat", "sliced turkey", "oven roasted turkey", "smoked turkey"),
    _f("salami", "deli meat", "genoa salami", days=14),
    _f("pepperoni", "deli meat", days=21),
    _f("hot dogs", "deli meat", "franks", "beef franks", "wieners", days=14),
    _f("bologna", "deli meat", days=7),
    _f("roast beef", "deli meat", "sliced roast beef"),
    # ---- Seafood ----
    _f("salmon", "seafood", "salmon fillet", "atlantic salmon", "fresh salmon"),
    _f("tilapia", "seafood", "tilapia fillets"),
    _f("cod", "seafood", "cod fillets"),
    _f("shrimp", "seafood", "raw shrimp", "jumbo shrimp"),
    _f("tuna steak", "seafood", "ahi tuna"),
    _f("crab", "seafood", "crab legs", "crab meat"),
    _f("scallops", "seafood"),
    _f("mussels", "seafood"),
    _f("catfish", "seafood", "catfish fillets"),
    # ---- Bakery ----
    _f("bread", "bakery", "white bread", "wheat bread", "whole wheat bread",
       "sandwich bread", "multigrain bread", days=7),
    _f("sourdough bread", "bakery", "sourdough"),
    _f("bagels", "bakery", "bagel", "plain bagels", "everything bagels", days=7),
    _f("english muffins", "bakery", "english muffin", days=7),
    _f("tortillas", "bakery", "flour tortillas", "corn tortillas", days=14),
    _f("hamburger buns", "bakery", "burger buns", "sandwich buns", days=7),
    _f("hot dog buns", "bakery", days=7),
    _f("croissants", "bakery", "croissant", days=3),
    _f("muffins", "bakery", "muffin", "blueberry muffins"),
    _f("donuts", "bakery", "doughnuts", "glazed donuts", days=3),
    _f("cake", "bakery", "birthday cake", days=4),
    _f("cookies", "bakery", "chocolate chip cookies", days=14),
    _f("pita bread", "bakery", "pita", days=7),
    _f("naan", "bakery", "naan bread", days=7),
    _f("dinner rolls", "bakery", "brioche rolls", days=7),
    _f("baguette", "bakery", "french bread", days=3),
    _f("pie", "bakery", "apple pie", "pumpkin pie", days=4),
    # ---- Frozen ----
    _f("ice cream", "frozen", "vanilla ice cream", "chocolate ice cream", days=90),
    _f("frozen pizza", "frozen", "pizza"),
    _f("frozen vegetables", "frozen", "frozen broccoli", "frozen peas", "frozen corn",
       "frozen mixed vegetables", days=300),
    _f("frozen fruit", "frozen", "frozen strawberries", "frozen berries",
       "frozen mango", days=300),
    _f("frozen waffles", "frozen", "waffles"),
    _f("frozen chicken nuggets", "frozen", "chicken nuggets", "nuggets"),
    _f("frozen french fries", "frozen", "french fries", "fries", "tater tots"),
    _f("frozen fish sticks", "frozen", "fish sticks"),
    _f("frozen burritos", "frozen", "burritos"),
    _f("frozen dinner", "frozen", "tv dinner", "frozen meal", "frozen entree"),
    _f("popsicles", "frozen", "ice pops"),
    _f("frozen dumplings", "frozen", "potstickers", "gyoza"),
    # ---- Pantry staples ----
    _f("rice", "pantry staples", "white rice", "brown rice", "jasmine rice", "basmati rice"),
    _f("pasta", "pantry staples", "spaghetti", "penne", "rotini", "macaroni", "fettuccine",
       "linguine", "elbow macaroni"),
    _f("ramen noodles", "pantry staples", "ramen", "instant noodles"),
    _f("flour", "pantry staples", "all purpose flour", "bread flour"),
    _f("sugar", "pantry staples", "granulated sugar", "brown sugar", "powdered sugar", days=720),
    _f("salt", "pantry staples", "table salt", "sea salt", "kosher salt", days=1800),
    _f("black pepper", "pantry staples", "pepper", "ground black pepper", days=720),
    _f("olive oil", "pantry staples", "extra virgin olive oil", days=540),
    _f("vegetable oil", "pantry staples", "canola oil", "cooking oil", days=540),
    _f("cereal", "pantry staples", "corn flakes", "cheerios", "granola", days=180),
    _f("oatmeal", "pantry staples", "oats", "rolled oats", "quick oats", "instant oatmeal"),
    _f("peanut butter", "pantry staples", days=270),
    _f("jelly", "pantry staples", "jam", "grape jelly", "strawberry jam", days=270),
    _f("honey", "pantry staples", days=1800),
    _f("pancake mix", "pantry staples"),
    _f("maple syrup", "pantry staples", "pancake syrup", days=540),
    _f("dried beans", "pantry staples", "pinto beans", "lentils"),
    _f("quinoa", "pantry staples"),
    _f("bread crumbs", "pantry staples", "panko"),
    _f("baking soda", "pantry staples", days=720),
    _f("baking powder", "pantry staples", days=540),
    _f("vanilla extract", "pantry staples", days=1800),
    _f("chocolate chips", "pantry staples", days=360),
    _f("coffee", "pantry staples", "ground coffee", "coffee beans", "instant coffee", days=180),
    _f("tea", "pantry staples", "tea bags", "green tea", "black tea", days=540),
    _f("nuts", "pantry staples", "almonds", "peanuts", "cashews", "walnuts",
       "mixed nuts", days=180),
    _f("raisins", "pantry staples", "dried cranberries", "dried fruit", days=360),
    # ---- Canned goods ----
    _f("canned tomatoes", "canned goods", "diced tomatoes", "crushed tomatoes", "tomato paste"),
    _f("tomato sauce", "canned goods"),
    _f("canned beans", "canned goods", "black beans", "kidney beans", "refried beans",
       "garbanzo beans", "chickpeas", "baked beans"),
    _f("canned corn", "canned goods"),
    _f("canned soup", "canned goods", "chicken noodle soup", "tomato soup", "soup"),
    _f("canned tuna", "canned goods", "tuna", "chunk light tuna"),
    _f("canned chicken", "canned goods"),
    _f("chicken broth", "canned goods", "chicken stock", "beef broth", "vegetable broth"),
    _f("canned green beans", "canned goods"),
    _f("canned fruit", "canned goods", "canned peaches", "canned pineapple", "fruit cocktail"),
    _f("coconut milk", "canned goods"),
    # ---- Beverages ----
    _f("orange juice", "beverages", "oj", days=10),
    _f("apple juice", "beverages", days=10),
    _f("soda", "beverages", "cola", "coke", "pepsi", "sprite", "soft drinks"),
    _f("sparkling water", "beverages", "seltzer", "club soda", days=270),
    _f("bottled water", "beverages", "water", "spring water", "drinking water", days=720),
    _f("sports drink", "beverages", "gatorade", "powerade", days=270),
    _f("energy drink", "beverages", "red bull", "monster", days=270),
    _f("lemonade", "beverages", days=10),
    _f("iced tea", "beverages", days=10),
    _f("beer", "beverages", days=180),
    _f("wine", "beverages", "red wine", "white wine", days=720),
    _f("kombucha", "beverages", days=30),
    # ---- Snacks ----
    _f("potato chips", "snacks", "chips"),
    _f("tortilla chips", "snacks", "corn chips", "nacho chips"),
    _f("pretzels", "snacks"),
    _f("popcorn", "snacks", "microwave popcorn"),
    _f("crackers", "snacks", "saltines", "cheese crackers", "graham crackers"),
    _f("granola bars", "snacks", "cereal bars", "protein bars", days=180),
    _f("fruit snacks", "snacks", days=180),
    _f("candy", "snacks", "chocolate", "chocolate bar", "gummy bears", days=180),
    _f("beef jerky", "snacks", "jerky", days=270),
    _f("rice cakes", "snacks"),
    _f("trail mix", "snacks", days=180),
    _f("applesauce", "snacks", "apple sauce", days=270),
    _f("pudding", "snacks", "pudding cups", days=180),
    # ---- Condiments & sauces ----
    _f("ketchup", "condiments & sauces"),
    _f("mustard", "condiments & sauces", "yellow mustard", "dijon mustard", days=365),
    _f("mayonnaise", "condiments & sauces", "mayo", days=90),
    _f("ranch dressing", "condiments & sauces", "ranch", days=90),
    _f("salad dressing", "condiments & sauces", "italian dressing", "caesar dressing", days=90),
    _f("bbq sauce", "condiments & sauces", "barbecue sauce", days=270),
    _f("hot sauce", "condiments & sauces", "sriracha", "tabasco", days=365),
    _f("soy sauce", "condiments & sauces", days=540),
    _f("salsa", "condiments & sauces", days=30),
    _f("pasta sauce", "condiments & sauces", "marinara sauce", "spaghetti sauce",
       "alfredo sauce", days=365),
    _f("pickles", "condiments & sauces", "dill pickles", days=365),
    _f("relish", "condiments & sauces", days=365),
    _f("vinegar", "condiments & sauces", "apple cider vinegar", "balsamic vinegar", days=1800),
    _f("worcestershire sauce", "condiments & sauces", days=540),
    _f("teriyaki sauce", "condiments & sauces", days=365),
    _f("olives", "condiments & sauces", "black olives", "green olives", days=365),
    # ---- Baby & health ----
    _f("baby food", "baby & health", days=365),
    _f("baby formula", "baby & health", "infant formula", days=365),
    _f("vitamins", "baby & health", "multivitamin", days=540),
    # ---- Household (non-food, tracked so scans don't fail on them) ----
    _f("paper towels", "household"),
    _f("toilet paper", "household", "bath tissue"),
    _f("dish soap", "household", "dishwashing liquid"),
    _f("laundry detergent", "household", "detergent"),
    _f("trash bags", "household", "garbage bags"),
    _f("aluminum foil", "household", "foil"),
    _f("plastic wrap", "household", "cling wrap"),
    _f("sandwich bags", "household", "ziploc bags", "storage bags"),
    _f("napkins", "household"),
    _f("hand soap", "household", "bar soap", "soap"),
    _f("shampoo", "household"),
    _f("toothpaste", "household"),
    _f("deodorant", "household"),
    _f("batteries", "household"),
    _f("light bulbs", "household"),
    _f("sponges", "household"),
    _f("bleach", "household"),
    _f("all purpose cleaner", "household", "cleaner", "disinfecting wipes"),
    _f("dog food", "household", "cat food", "pet food"),
    _f("cat litter", "household"),
)


def shelf_life_for(info: FoodInfo) -> int:
    """Effective shelf life in days for a food item."""
    if info.shelf_life_days is not None:
        return info.shelf_life_days
    return CATEGORY_SHELF_LIFE.get(info.category, DEFAULT_SHELF_LIFE_DAYS)
